global:
  bucketName: "{{ .config.prefix }}-{{ .module.name }}-metrics"
  google:
    hostname: "{{ .module.name }}.{{ .toutput.dns.int_domain }}"
    projectID: "{{ .toutput.crossplane.project_id }}"
    bucket:
      location: "{{ .toutput.gke.region }}"
mimir-distributed:
  gateway:
    nginx:
      image:
        registry: '{{ .toptout.gar-proxy.hub_registry | "docker.io" }}'
  image:
    repository: '{{ .toptout.gar-proxy.hub_registry | "docker.io" }}/grafana/mimir'
  nginx:
    image:
      registry: '{{ .toptout.gar-proxy.hub_registry | "docker.io" }}'
