global:
  cloudProvider: ""
  providerConfigRefName: ""
  bucketName: "mimir"
  prefix: ""


mimir-distributed:
  fullnameOverride: mimir
  serviceAccount:
    create: false
    name: mimir

  alertmanager:
    enabled: false

  distributor:
    replicas: 1

    podAnnotations:
      kube-score/ignore: pod-probes,pod-networkpolicy

    resources:
      limits:
        cpu: 2
        memory: 2Gi
        ephemeral-storage: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi
        ephemeral-storage: 128Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  ingester:
    replicas: 3 #3
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    zoneAwareReplication:
      enabled: false
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    statefulSet:
      enabled: true
    podAnnotations:
      kube-score/ignore: pod-probes,pod-networkpolicy

    resources:
      limits:
        cpu: 2
        memory: 8Gi
        ephemeral-storage: 10Gi
      requests:
        cpu: 100m
        memory: 2Gi
        ephemeral-storage: 128Mi

    persistentVolume:
      enabled: true
      size: 50Gi

  overrides_exporter:
    enabled: true
    replicas: 1
    podAnnotations:
      kube-score/ignore: pod-probes,pod-networkpolicy

    resources:
      limits:
        cpu: 2
        memory: 2Gi
        ephemeral-storage: 2Gi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 128Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  ruler:
    enabled: true
    replicas: 1
    podAnnotations:
      kube-score/ignore: pod-probes,pod-networkpolicy

    resources:
      limits:
        cpu: 2
        memory: 2Gi
        ephemeral-storage: 2Gi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 128Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  querier:
    replicas: 2
    podAnnotations:
      kube-score/ignore: pod-probes,pod-networkpolicy

    resources:
      limits:
        cpu: 2
        memory: 2Gi
        ephemeral-storage: 2Gi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 128Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  query_frontend:
    replicas: 1
    podAnnotations:
      kube-score/ignore: pod-probes,pod-networkpolicy

    resources:
      limits:
        cpu: 2
        memory: 2Gi
        ephemeral-storage: 2Gi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 128Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  query_scheduler:
    enabled: false
    replicas: 2
    podAnnotations:
      kube-score/ignore: pod-probes,pod-networkpolicy

    resources:
      limits:
        cpu: 2
        memory: 2Gi
        ephemeral-storage: 2Gi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 128Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  store_gateway:
    # -- Total number of replicas for the store-gateway across all availability zones
    # If store_gateway.zoneAwareReplication.enabled=false, this number is taken as is.
    # Otherwise each zone starts `ceil(replicas / number_of_zones)` number of pods.
    #   E.g. if 'replicas' is set to 4 and there are 3 zones, then 4/3=1.33 and after rounding up it means 2 pods per zone are started.
    replicas: 3 #1

    podAnnotations:
      kube-score/ignore: pod-probes,pod-networkpolicy

    resources:
      limits:
        cpu: 2
        memory: 2Gi
        ephemeral-storage: 10Gi
      requests:
        cpu: 100m
        memory: 512Mi
        ephemeral-storage: 512Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    persistentVolume:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 50Gi
    zoneAwareReplication:
      enabled: false

  compactor:
    replicas: 1 #1
    podAnnotations:
      kube-score/ignore: pod-probes,pod-networkpolicy

    resources:
      limits:
        cpu: 2
        memory: 2Gi
        ephemeral-storage: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi
        ephemeral-storage: 128Mi
    persistentVolume:
      enabled: true
      size: 50Gi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  memcachedExporter:
    # -- Whether memcached metrics should be exported
    enabled: true

  chunks-cache:
    # -- Specifies whether memcached based chunks-cache should be enabled
    enabled: false
    replicas: 1
    allocatedMemory: 8192
    maxItemMemory: 1
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  index-cache:
    enabled: false
    replicas: 1
    allocatedMemory: 2048
    maxItemMemory: 5
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  metadata-cache:
    # -- Specifies whether memcached based metadata-cache should be enabled
    enabled: false
    replicas: 1
    allocatedMemory: 512
    maxItemMemory: 1
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  results-cache:
    enabled: false
    replicas: 1
    allocatedMemory: 512
    maxItemMemory: 1
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  # -- Setting for the Grafana Rollout Operator https://github.com/grafana/helm-charts/tree/main/charts/rollout-operator
  rollout_operator:
    enabled: false
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  minio:
    enabled: false

  # -- DEPRECATED: use the 'gateway' section instead. For a migration guide refer to
  # https://grafana.com/docs/mimir/latest/operators-guide/deploying-grafana-mimir/migrate-to-unified-gateway-deployment/
  #
  # Configuration for nginx gateway.
  # Can only be enabled when 'enterprise.enabled' is false.
  nginx:
    # -- Specifies whether nginx should be enabled
    enabled: false

  gateway:
    enabledNonEnterprise: true
    replicas: 3
    podAnnotations:
      kube-score/ignore: pod-probes,pod-networkpolicy
    resources:
      limits:
        cpu: 2
        memory: 2Gi
        ephemeral-storage: 2Gi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 128Mi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  metaMonitoring:
    serviceMonitor:
      enabled: false
    prometheusRule:
      enabled: false
    grafanaAgent:
      enabled: false
  enterprise:
    enabled: false
  tokengenJob:
    enable: false
  graphite:
    enabled: false
  gr-aggr-cache:
    enabled: false
  gr-metricname-cache:
    enabled: false
  continuous_test:
    enabled: false

