global:
  aws:
    account: "{{ .toutput.eks.account }}"
    clusterOIDC: "{{ .toutput.eks.oidc_provider }}"
cluster-autoscaler:
  awsRegion: "{{ .toutput.eks.region }}"
  autoDiscovery:
    clusterName: "{{ .toutput.eks.cluster_name }}"
  image:
    repository: '{{ .toptout.ecr-proxy.k8s_registry | "registry.k8s.io" }}/autoscaling/cluster-autoscaler'
