global:
  cloudProvider: "google"
  providerConfigRefName: "crossplane-google"

  google:
    projectID: ""
    hostname: ""
    gateway:
      name: google-gateway-internal
      namespace: google-gateway

grafana:
  ingress:
    enabled: false
  persistence:
    storageClassName: "standard"
