global:
  aws:
    account: "{{ .toutput.eks.account }}"
    clusterOIDC: "{{ .toutput.eks.oidc_provider }}"
    region: "{{ .toutput.eks.region }}"
    kmsKeyId: "{{ .toptout.kms.telemetry_alias_arn }}"
  bucketName: "{{ .config.prefix }}-{{ .module.name }}-{{ .toutput.eks.account }}-{{ .toutput.eks.region }}"
loki:
  gateway:
    image:
      registry: '{{ .toptout.ecr-proxy.hub_registry | "docker.io" }}'
    ingress:
      hosts:
        - host: "{{ .module.name }}.{{ .toutput.route53.int_domain }}"
          paths:
            - path: "/"
              pathType: "Prefix"
  loki:
    storage:
      s3:
        region: "{{ .toutput.eks.region }}"
      bucketNames:
        chunks: "{{ .config.prefix }}-{{ .module.name }}-{{ .toutput.eks.account }}-{{ .toutput.eks.region }}"
        ruler: "{{ .config.prefix }}-{{ .module.name }}-{{ .toutput.eks.account }}-{{ .toutput.eks.region }}"
        admin: "{{ .config.prefix }}-{{ .module.name }}-{{ .toutput.eks.account }}-{{ .toutput.eks.region }}"
    storage_config:
      aws:
        region: "{{ .toutput.eks.region }}"
        bucketnames: "{{ .config.prefix }}-{{ .module.name }}-{{ .toutput.eks.account }}-{{ .toutput.eks.region }}"
    image:
      registry: '{{ .toptout.ecr-proxy.hub_registry | "docker.io" }}'
  sidecar:
    image:
      repository: '{{ .toptout.ecr-proxy.hub_registry | "docker.io" }}/kiwigrid/k8s-sidecar'
