{{- if eq .Values.global.cloudProvider "google" }}

# Kubernetes Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.grafana.serviceAccount.name }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.grafana.serviceAccount.name }}@{{ .Values.global.google.projectID }}.iam.gserviceaccount.com"

---

# Google Service Account
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: {{ .Values.grafana.serviceAccount.name }}
spec:
  forProvider:
    displayName: Grafana Service Account
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
