global:
  aws:
    scheme: internet-facing
    groupName: external
    additionalIngressAnnotations: {}

ingress:
  hostName: ""

targetService: ""

secretStore: 
  name: ""
  kind: ClusterSecretStore
  
image:
  registry: docker.io/priitrent/saml-proxy
  tag: "40-20240809-1"
