global:
  cloudProvider: google
  providerConfigRefName: crossplane-google

  google:
    hostname: ""
    gateway:
      name: google-gateway-internal
      namespace: google-gateway

prometheus:
  server:
    ingress:
      enabled: false
