{{- if and (eq .Values.global.cloudProvider "aws") .Values.global.createClusterSecretStore }}

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    helm.sh/resource-policy: keep
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{.Values.global.aws.region}}
      auth:
        jwt:
          serviceAccountRef:
            name: secret-manager-operator
            namespace: {{ .Release.Namespace }}

{{- end }}
