global:
  cloudProvider: aws
  providerConfigRefName: crossplane-aws

  aws:
    account: ""
    clusterOIDC: ""
    assumeRole: ""

external-dns:
  sources:
    - service
    - ingress
    - istio-gateway
    - istio-virtualservice
    
  provider:
    name: aws
  env:
    - name: AWS_DEFAULT_REGION
      value: ""
  serviceAccount:
    create: false
