global:
  cloudProvider: ""
  providerConfigRefName: ""
external-dns:
  registry: txt
  policy: upsert-only
  extraArgs:
    - --metrics-address=:7979
  serviceAccount:
    name: "external-dns"
  serviceMonitor:
    enabled: false
    scrapeTimeout: 20s
    additionalLabels:
      kubernetes.io/metadata.name: monitoring
      release: prometheus
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
              - key: tools
                operator: In
                values:
                  - "true"
  tolerations:
    - key: "tools"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
      ephemeral-storage: 1Gi
    requests:
      cpu: 5m
      memory: 64Mi
      ephemeral-storage: 24Mi

  deploymentAnnotations:
    kube-score/ignore: pod-networkpolicy,pod-probes
