{{- if .Values.installCompositeResources }}
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: developer-portal-function
spec:
  runtimeConfigRef:
    name: developer-portal-function
  package: {{ .Values.function.repository }}:{{ .Values.function.tag }}
  packagePullSecrets:
    - name: developer-portal-regcred
{{- end }}
