{{- if .Values.installCompositeResources }}
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositewebapps.flow.entigo.io
spec:
  group: flow.entigo.io
  names:
    kind: CompositeWebapp
    plural: compositewebapps
  claimNames:
    kind: WebApp
    plural: webapps
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - apiVersion
            - kind
            - metadata
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              required:
                - name
                - namespace
              properties:
                name:
                  type: string
                namespace:
                  type: string
                labels:
                  type: object
                  propertyNames:
                    pattern: ^[A-Za-z][A-Za-z0-9_./-]*$
            spec:
              type: object
              properties:
                kind:
                  type: string
                architecture:
                  type: string
                replicas:
                  type: integer
                  format: int32
                  default: 1
                  min: 1
                restartPolicy:
                  type: string
                  enum:
                    - Always
                    - OnFailure
                    - Never
                  default: Always
                imagePullSecrets:
                  type: array
                  items:
                    type: string
                initContainers:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - registry
                      - repository
                    properties:
                      name:
                        type: string
                      registry:
                        type: string
                      repository:
                        type: string
                      tag:
                        type: string
                      command:
                        type: array
                        items:
                          type: string
                      resources:
                        type: object
                        properties:
                          limits:
                            type: object
                            properties:
                              cpu:
                                type: number
                              ram:
                                type: number
                      environment:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                            secret:
                              type: boolean
                              default: false
                      livenessProbe:
                        type: object
                        properties:
                          path:
                            type: string
                          port:
                            type: string
                          initialDelaySeconds:
                            type: integer
                            format: int32
                            min: 0
                            default: 0
                          periodSeconds:
                            type: integer
                            format: int32
                            min: 1
                            default: 10
                          timeoutSeconds:
                            type: integer
                            format: int32
                            min: 1
                            default: 1
                          successThreshold:
                            type: integer
                            format: int32
                            min: 1
                            default: 1
                          failureThreshold:
                            type: integer
                            format: int32
                            min: 1
                            default: 3
                          terminationGracePeriodSeconds:
                            type: integer
                            format: int32
                            min: 1
                            default: 30
                containers:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - registry
                      - repository
                    properties:
                      name:
                        type: string
                      registry:
                        type: string
                      repository:
                        type: string
                      tag:
                        type: string
                      command:
                        type: array
                        items:
                          type: string
                      exposedPort:
                        type: string
                      resources:
                        type: object
                        properties:
                          limits:
                            type: object
                            properties:
                              cpu:
                                type: number
                              ram:
                                type: number
                      services:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            port:
                              type: integer
                              format: int32
                              min: 1024
                              max: 65535
                            protocol:
                              type: string
                              enum:
                                - TCP
                                - SCTP
                                - UDP
                                - GRPC
                              default: TCP
                      environment:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                            secret:
                              type: boolean
                              default: false
                      livenessProbe:
                        type: object
                        properties:
                          path:
                            type: string
                          port:
                            type: string
                          initialDelaySeconds:
                            type: integer
                            format: int32
                            min: 0
                            default: 0
                          periodSeconds:
                            type: integer
                            format: int32
                            min: 1
                            default: 10
                          timeoutSeconds:
                            type: integer
                            format: int32
                            min: 1
                            default: 1
                          successThreshold:
                            type: integer
                            format: int32
                            min: 1
                            default: 1
                          failureThreshold:
                            type: integer
                            format: int32
                            min: 1
                            default: 3
                          terminationGracePeriodSeconds:
                            type: integer
                            format: int32
                            min: 1
                            default: 30
{{- end }}
