# {{- if eq .Values.global.cloudProvider "aws" }}
# 
# apiVersion: s3.aws.crossplane.io/v1beta1
# kind: Bucket
# metadata:
#   name: {{ .Values.harbor.persistence.imageChartStorage.s3.bucket }}
#   annotations:
#     crossplane.io/external-name: {{ .Values.harbor.persistence.imageChartStorage.s3.bucket }}
# spec:
#   forProvider:
#     acl: private
#     locationConstraint: {{ .Values.harbor.persistence.imageChartStorage.s3.region }}
#     objectOwnership: BucketOwnerPreferred
#     publicAccessBlockConfiguration:
#       blockPublicPolicy: true
#       blockPublicAcls: true
#       ignorePublicAcls: true
#       restrictPublicBuckets: true
#     accelerateConfiguration:
#       status: Enabled
#     versioningConfiguration:
#       status: Suspended
#     serverSideEncryptionConfiguration:
#       rules:
#       - applyServerSideEncryptionByDefault:
#           {{- if .Values.global.aws.kmsKeyId }}
#           kmsMasterKeyId: {{ .Values.global.aws.kmsKeyId }}
#           sseAlgorithm: aws:kms
#           {{- else }}
#           sseAlgorithm: AES256
#           {{- end }}
#   providerConfigRef:
#     name: {{ .Values.global.providerConfigRefName }}
# 
# {{- end }}
