global:
  google:
    hostname: "{{ .module.name }}.{{ .toutput.dns.pub_domain }}"
    projectID: "{{ .toutput.crossplane.project_id }}"
    bucket:
      location: "{{ .toutput.gke.region }}"
harbor:
  externalURL: "https://{{ .module.name }}.{{ .toutput.dns.pub_domain }}"
  persistence:
    imageChartStorage:
      gcs:
        bucket: "{{ .config.prefix }}-{{ .module.name }}"
