apiVersion: v2
name: harbor
description: A Harbor Registry chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: harbor
  version: 1.16.2
  repository: https://helm.goharbor.io
