global:
  cloudProvider: ""
  providerConfigRefName: ""

resources:
  limits:
    cpu: 1
    memory: 1204Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 10m
    memory: 64Mi
    ephemeral-storage: 10Mi

installCompositeResources: true
config: {}

image:
  repository: docker.io/entigolabs/developer-portal-agent
  tag: main-62

function:
  repository: docker.io/entigolabs/function-flow-web-access
  tag: v0.0.0-20240807123315-1be423dde9fe
