global:
  cloudProvider: ""

kiali-server:
  istio_namespace: "istio-system"
  server:
    web_fqdn: ""
  external_services:
    prometheus:
      url: ""
  deployment:
    image_pull_policy: "IfNotPresent"
    instance_name: "kiali"
    pod_annotations:
      kube-score/ignore: pod-probes,pod-networkpolicy
    affinity:
      node:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    resources:
      limits:
        cpu: 2000m
        memory: 1Gi
        ephemeral-storage: 1Gi
      requests:
        cpu: "10m"
        memory: "64Mi"
        ephemeral-storage: 10Mi
