{{- if eq .Values.global.cloudProvider "aws" }}
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: {{ .Release.Name }}
spec:
  forProvider:
    name: {{ .Release.Name }}
    tags:
      - key: created-by
        value: entigo-infralib
    document: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Action": [
                    "ecr:GetRegistryPolicy",
                    "ecr:DescribeImageScanFindings",
                    "ecr:GetLifecyclePolicyPreview",
                    "ecr:GetDownloadUrlForLayer",
                    "ecr:DescribeRegistry",
                    "ecr:DescribeImageReplicationStatus",
                    "ecr:GetAuthorizationToken",
                    "ecr:ListTagsForResource",
                    "ecr:BatchGetRepositoryScanningConfiguration",
                    "ecr:GetRegistryScanningConfiguration",
                    "ecr:BatchGetImage",
                    "ecr:DescribeImages",
                    "ecr:DescribeRepositories",
                    "ecr:BatchCheckLayerAvailability",
                    "ecr:GetRepositoryPolicy",
                    "ecr:GetLifecyclePolicy"
                  ],
                  "Effect": "Allow",
                  "Resource": "*"
              },
              {
                      "Action": [
                              "events:DescribeRule",
                              "events:PutRule",
                              "events:PutTargets",
                              "events:ListTargetsByRule"
                      ],
                      "Effect": "Allow",
                      "Resource": "*"
              },
              {
                  "Action": [
                      "sqs:DeleteMessage",
                      "sqs:ReceiveMessage"
                  ],
                  "Effect": "Allow",
                  "Resource": "arn:aws:sqs:{{ .Values.global.aws.region }}:{{ .Values.global.aws.account }}:*"
              },
              {
                  "Action": "sts:AssumeRole",
                  "Effect": "Allow",
                  "Resource": "arn:aws:iam::{{ .Values.global.aws.account }}:role/{{ .Release.Name }}-ecr-push"
              }
          ]
      }
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: {{ .Release.Name }}-ecr-push
spec:
  forProvider:
    name: {{ .Release.Name }}-ecr-push
    document: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Action": [
                      "ecr:BatchGetImage",
                      "ecr:GetDownloadUrlForLayer",
                      "ecr:CompleteLayerUpload",
                      "ecr:UploadLayerPart",
                      "ecr:InitiateLayerUpload",
                      "ecr:BatchCheckLayerAvailability",
                      "ecr:PutImage"
                  ],
                  "Resource": "arn:aws:ecr:{{ .Values.global.aws.region }}:{{ .Values.global.aws.account }}:repository/*"
              },
              {
                  "Effect": "Allow",
                  "Action": [
                      "ecr:GetAuthorizationToken"
                  ],
                  "Resource": "*"
              }
          ]
      }
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
{{- end }}
