     
istiod:
  global:
    imagePullPolicy: "IfNotPresent"
    defaultResources:
      requests:
        cpu: 10m
        memory: 32Mi
        ephemeral-storage: 10Mi
      limits:
        cpu: 2000m
        memory: 512Mi
        ephemeral-storage: 1Gi
  pilot:
    autoscaleMin: 2
    replicaCount: 2
    podAnnotations:
      kube-score/ignore: pod-networkpolicy
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
            - key: tools
              operator: In
              values:
              - "true"
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    resources:
      requests:
        cpu: 5m
        memory: 160Mi
        ephemeral-storage: 100Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
        ephemeral-storage: 1Gi
