apiVersion: v2
name: istio-base
description: istio-base
version: 0.1.0
appVersion: "0.1.0"

dependencies:
- name: base
  version: 1.24.3
  repository: https://istio-release.storage.googleapis.com/charts
