apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    category: application
data:
  {{- if eq .Values.global.cloudProvider "aws" }}
  REGISTRIES: "{{ .Values.global.aws.account }}.dkr.ecr.{{ .Values.global.aws.region }}.amazonaws.com"
  EVENTS_SQS_URL: "https://sqs.{{ .Values.global.aws.region }}.amazonaws.com/{{ .Values.global.aws.account }}/{{ .Release.Name }}"
  ASSUME_ROLE_ARN: "arn:aws:iam::{{ .Values.global.aws.account }}:role/{{ .Release.Name }}-ecr-push"
  {{- end }}
  RESOURCES_FILE: "/config/resources.yaml"
{{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-resources
  labels:
    category: application
data:
  resources.yaml: |-
    resources:
      - group: flow.entigo.io
        version: v1alpha1
        resources:
          - webapps
          - webaccesses
          - cronjobs
    globalResources:
      - group: flow.entigo.io
        version: v1alpha1
        resources:
          - compositerepositories
      - group: karpenter.sh
        version: v1
        resources:
          - nodepools
    globalStatusResources:
      - group: karpenter.sh
        version: v1
        resources:
          - nodeclaims
      - group: karpenter.k8s.aws
        version: v1
        resources:
          - ec2nodeclasses
      - group: ""
        version: v1
        resources:
          - nodes
    statusResources:
      - group: ""
        version: v1
        resources:
          - pods
      - group: "apps"
        version: v1
        resources:
          - replicasets
          - deployments
      - group: "argoproj.io"
        version: v1alpha1
        resources:
          - applications
    mutateResources:
      - group: flow.entigo.io
        version: v1alpha1
        resources:
          - ociloginrequests
