apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if eq .Values.global.cloudProvider "aws" }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.aws.account }}:role/{{ .Release.Name }}
  {{- end }}
  name: {{ .Release.Name }}
